### ISSUE TITLE
(Advice) Trusted dictionary is always empty - Should we load from certifi?

### ISSUE THREAD

**Issue by IMG-PRCSNG** [danilobellini/aia#1]
System info:
OS: Ubuntu 20.04
Python version: 3.8.10
aia: from master ([4104b96](https://github.com/danilobellini/aia/commit/4104b9667526986198e08f7e14a8d2b7497ea12c))

Thanks for the neat utility!

I was giving it a go and noticed that [self._trusted](https://github.com/danilobellini/aia/blob/4104b9667526986198e08f7e14a8d2b7497ea12c/aia.py#L104) always turns up empty on my system. [Documentation](https://docs.python.org/3/library/ssl.html#ssl.SSLContext.get_ca_certs) says the list will not contain a path unless loaded by ssl connections.

Code to reproduce

```py
>>>
import ssl
a = ssl.create_default_context()
a.load_default_certs()
print(a.get_ca_certs())

# Outputs an empty list on Ubuntu 20.04, python 3.8.10
# >>> []
```

Should the [`_trusted`](https://github.com/danilobellini/aia/blob/4104b9667526986198e08f7e14a8d2b7497ea12c/aia.py#L104) variable be manually populated with trusted certificates (eg: from `certifi`) after initialising a session?

Cheers!

**Comment by danilobellini** [comment]
In Ubuntu, you can install the `ca-certificates` (from the APT repositories) and set the environment variable `SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt`. That should have been the default configuration, but as you can see with `ssl.get_default_verify_paths()`, it will look for the `/usr/lib/ssl/cert.pem` file, which doesn't exist.

Maybe the `__init__` should change to handle this, but I would need to check in which OS/distros this happen, and how to get the root certificates from `certifi` or other source in case they can't be found in the default location. Anyway, updating `_trusted` manually after initialization should be okay for the current version of `aia` (v0.2.0), if that system-level solution based on an environment variable isn't an alternative.

**Comment by IMG-PRCSNG** [comment]
Thanks a lot for the detailed answer!

I didn't know about the ENV vars. TIL!

My workaround was overriding the constructor.
```
import certifi
from aia import AIASession, openssl_get_cert_info

class CustomSession(AIASession):
    def __init__(self, user_agent=DEFAULT_USER_AGENT):
        self.user_agent = user_agent
         self._context = ssl.create_default_context()
         self._context.load_default_certs()
         self._context.load_verify_locations(certifi.where())

        # Trusted certificates whitelist in dict format like:
        # {"RFC4514 string": b"DER certificate contents"}
        self._trusted = {
            openssl_get_cert_info(ca_der)["subject"]: ca_der
            for ca_der in self._context.get_ca_certs(True)
        }
```

Cheers!

**Comment by yan12125** [comment]
FWIW, I have a similar issue, and the issue is gone after I switched from Ubuntu 22.04 to 24.04. Probably it's related to https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=805646
